apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
spec:
  selector:
    app:  glance
  ports:
  - protocol: TCP
    port:  8080
    targetPort:  8080
    nodePort: 30090  # Choose any available port (30000-32767)
  type: NodePort
