apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: full
            widgets:
              - type: rss
                hide-header: true
                cache: 12h
                title: Arch Updates
                feeds:
                  - url: https://archlinux.org/feeds/news/
                    title: Arch News

              - type: monitor
                hide-header: true
                cache: 1m
                title: Services
                sites:
                - title: Rancher
                  url: https://rancher.k3s.milliways.fi
                - title: Portainer
                  url: https://portainer.k3s.milliways.fi
                - title: Nginx Proxy Manager
                  url: http://npm.milliways.fi

          - size: small
            widgets:
              - type: calendar
                hide-header: true
                first-day-of-week: monday

              - type: weather
                hide-header: true
                location: Tampere, Finland
                units: metric

