apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-https
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.k3s.milliways.fi`)
      kind: Rule
      services:
        - name: portainer
          port: 9443
          scheme: https
          serversTransport: portainer-transport
  tls:
    secretName: portainer-tls
