named_conf_template: "named.conf.j2"
named_conf_dest: "/etc/named.conf"
dns_zone_template: "named.milliways.fi.j2"
dns_zone_config_dest: "/var/named/named.milliways.fi"
reverse_zone_template: "reverse.zone.j2"
dns_reverse_zones: []
# group list for dns nmcli setting
group_dns_servers: "192.168.10.5,192.168.10.6"
nm_conn_name: "eth0"
