---
- name: Deploy k3s control plane
  hosts: k3s_control_plane
  become: true
  roles:
    - common
    - k3s_vm
    - k3s_server

- name: Deploy k3s worker nodes
  hosts: k3s_workers
  become: true
  roles:
    - common
    - k3s_vm
    - k3s_agent
