---
- name: Setup k3s control plane
  hosts: k3s_control_plane
  become: true
  roles:
    - role: ../../roles/k3s_server

- name: Setup k3s worker nodes
  hosts: k3s_workers
  become: true
  roles:
    - role: ../../roles/k3s_agent
