---
- name: Install k3s agent and join cluster
  ansible.builtin.command:
    argv:
      - /bin/sh
      - /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_URL: "https://192.168.20.21:6443"
    K3S_TOKEN: "TOSI-HIENO-TOKEN"
  become: true

- name: Restart k3s-agent service
  ansible.builtin.systemd_service:
    name: k3s-agent
    state: restarted

